import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const testRoot = path.dirname(fileURLToPath(import.meta.url));
const artifactRoot = path.dirname(testRoot);
const read = (relativePath) => fs.readFileSync(path.join(artifactRoot, relativePath), "utf8");

const html = read("src/index.html");
const legacy = read("src/legacy/app.js");
const estates = read("src/features/data-grid/estates-grid.js");
const docPrepRegister = read("src/features/doc-prep/register.js");
const docPrepView = read("src/features/doc-prep/s40-doc-prep-view.js");
const docPrepCss = read("src/features/doc-prep/s40-doc-prep.css");
const operationalRails = read("src/features/beui-runtime/operational-grid-rails.tsx");
const gridCss = read("src/features/data-grid/grids.css");
const queueGrid = read("src/features/data-grid/queue-grid.js");
const adminAuditGrid = read("src/features/data-grid/admin-audit-grid.js");
const shellCss = read("src/features/shell/shell.css");
const legacyCss = read("src/styles/legacy.css");
const exportView = read("src/features/estate-export/export-view.js");
const exportRegister = read("src/features/estate-export/register.js");
const shellView = read("src/features/shell/shell-view.js");
const shellController = read("src/features/shell/shell-controller.js");
const compatCss = read("src/styles/compat.css");
const dashboardCss = read("src/features/dashboard/dashboard.css");
const tokensCss = read("src/styles/tokens.css");

assert.match(operationalRails, /renderOperationalGridRail/);
assert.match(operationalRails, /Table, type TableColumn/);
assert.match(operationalRails, /case "estates"[\s\S]*case "queue"[\s\S]*case "export"[\s\S]*case "admin-audit"[\s\S]*case "shell-queue"/);
assert.doesNotMatch(gridCss, /ag-grid|data-community-grid|\.ag-root/);
assert.match(gridCss, /\.hr-grid-controls[\s\S]*flex-wrap: wrap/);
assert.match(gridCss, /\.hr-grid-action-status[\s\S]*flex: 1 1 100%/);
assert.match(gridCss, /\.hr-grid-header > div:first-child[\s\S]*flex: 0 1 24rem/);
assert.match(gridCss, /\.hr-grid-header > div:first-child[\s\S]*min-width: 16rem/);
assert.match(gridCss, /\.hr-grid-controls[\s\S]*flex: 1 1 auto/);
for (const [surface, source] of [["Estates", estates], ["Queue", queueGrid], ["Export", exportView], ["Admin", adminAuditGrid]]) {
  assert.match(source, /data-beui-rail/, `${surface} must mount a BeUI rail slot`);
  assert.doesNotMatch(source, /createCommunityGrid|data-community-grid/);
}
assert.match(shellController, /data-beui-rail=\\"shell-queue\\"/);
assert.match(shellController, /heirright:beui-rail-render/);

const nav = [...html.matchAll(/data-shell-nav="([^"]+)"/g)].map((match) => match[1]);
assert.deepEqual(nav.slice(0, 4), ["dashboard", "find-estates", "dossiers", "admin"]);
assert.doesNotMatch(nav.join(" "), /home|queue/i, "the primary loop must not expose Home or a duplicate Queue tab");
assert.equal(nav[0], "dashboard");
assert.equal(nav.filter((view) => view === "dashboard").length, 1, "Manage Estates must retain one legacy dashboard route");
assert.equal(nav.includes("export"), false, "Export stays available only through the verified handoff surface");
assert.equal(nav.includes("drips"), false, "Outreach is hidden until its loop is ready");
assert.match(html, /data-hover-label="Manage Estates"/);
assert.match(html, /<span class="nav-label">Manage Estates<\/span>/);
assert.doesNotMatch(html, /data-hover-label="Dashboard"/);
assert.match(html, /<section class="app" data-active-view="dashboard"/);
assert.match(html, /data-view-panel="export"/);
assert.match(html, /data-drawer-mode="activity"/);
assert.match(shellCss, /agent-drawer\[data-drawer-mode="activity"\]/);
assert.match(shellCss, /agent-drawer\[data-drawer-mode="admin"\]/);
assert.ok(legacyCss.includes("grid-template-columns: minmax(0, 7fr) minmax(18rem, 3fr)"));
assert.ok(legacyCss.includes("#adminView .admin-tall-grid > .loop-panel:nth-child(1) { display: none; }"));

for (const state of ["active", "queued", "processing", "completed-awaiting-export", "exported", "blocked"]) {
  assert.match(legacy, new RegExp(`"${state}"`), `missing persisted lifecycle state: ${state}`);
}
assert.match(legacy, /heirright:estate-workflow-state/);
assert.match(legacy, /function setEstateWorkflowState/);
assert.match(legacy, /estateWorkflowTransitions/);
assert.match(legacy, /function queueEstatesForDocPrep/);
assert.match(legacy, /function ensureS40WorkflowStateReady/);
assert.match(legacy, /hasReplacement = typeof replacement === "string"/);
assert.match(legacy, /const initialView = productViews\.includes\(initialViewParam\) \? initialViewParam : "dashboard"/);
assert.match(legacy, /function csvFileImportItems/);
assert.match(legacy, /estateFileImportMaxBytes/);
assert.match(legacy, /async function base64ForEstateFile/);
assert.match(legacy, /async function queueEstateFile/);
assert.match(legacy, /postJson\("\/api\/agentic\/estate-import"/);
assert.match(legacy, /freeModelVerified/);
assert.match(legacy, /data-estate-upload-dropzone/);
assert.match(legacy, /data-crm-upload-retry/);
assert.match(legacy, /data-crm-upload-remove/);
assert.match(legacy, /role="progressbar"/);
assert.match(legacy, /status: "queued"/);
assert.match(legacy, /async function commitEstateFileImports/);
assert.match(legacy, /function estateFileImportItems/);
assert.doesNotMatch(legacy, /async function submitBatchCrmImport|function csvImportItem|crmImportCsvFile/);
assert.match(legacy, /crmBatchImportLimit = 250/);
assert.match(legacy, /slice\(0, crmBatchImportLimit\)/);
assert.match(legacy, /await ensureS40WorkflowStateReady\(\)/);
assert.match(legacy, /requestedIds\s*\.map\(\(estateId\) => \[estateId, rowById\(estateId\)\]\)/);
assert.match(legacy, /function runS40DocPrep/);
assert.match(legacy, /function stopS40DocPrep/);
assert.match(legacy, /s40-stop-docprep/);
assert.match(legacy, /function idiImportReadyForDocPrep/);
assert.match(legacy, /idiReportReady/);
assert.match(legacy, /function exportS40Handoff/);
assert.match(legacy, /function publicDiscoveryPreview/);
assert.match(legacy, /discoveryPreview/);
assert.match(legacy, /s40-queue-estates/);
assert.match(legacy, /s40-run-docprep/);
assert.match(legacy, /s40-approve-packet/);
assert.match(legacy, /s40-export-handoff/);
assert.match(legacy, /exportEligible/);
assert.match(legacy, /readbackStatus === "verified"/);
assert.match(legacy, /linkGeneratedDocPrepPackets\(row, "discovery"/);
assert.match(legacy, /verifyGeneratedPacketAuditReadback\(row, "discovery"\)/);
const s40RunBody = legacy.slice(legacy.indexOf("async function runS40DocPrep"), legacy.indexOf("async function exportS40Handoff"));
assert.doesNotMatch(s40RunBody, /runAutonomousDiscoverySources|external-source-run|live_idi_core/i, "the S40 run must consume persisted evidence and avoid new provider runs");

assert.match(estates, /function activeEstateRows/);
assert.match(estates, /workflowState === "active"/);
assert.match(estates, /s40-queue-estates/);
assert.doesNotMatch(estates, /bridge\.dispatch\("export", \{ route: "queue"/);

assert.match(docPrepRegister, /s40-doc-prep/);
assert.match(docPrepRegister, /s40-doc-prep-view/);
assert.doesNotMatch(docPrepRegister, /docPrepRail|renderDocPrepView/);
assert.match(docPrepView, /s40-workbench/);
assert.match(docPrepView, /data-s40-beui-queue/);
assert.match(docPrepView, /data-s40-beui-batch-progress/);
assert.match(docPrepView, /rows\.length > 1[\s\S]*workflowBatchId/);
assert.doesNotMatch(docPrepView, /data-community-grid="docprep"|createCommunityGrid|setGridQuickFilter/);
assert.match(docPrepView, /data-s40-run/);
assert.match(docPrepView, /data-s40-stop/);
assert.match(docPrepView, /data-stop-docprep/);
assert.match(docPrepView, /idiReportReady/);
assert.match(docPrepView, /s40-discovery-page-footer/);
assert.match(docPrepView, /pages\.length/);
assert.match(docPrepView, /data-s40-export/);
assert.match(docPrepView, /iframe/);
assert.match(docPrepView, /Verified internal PDF/);
assert.match(docPrepView, /renderDiscoveryTemplatePreview/);
assert.match(docPrepView, /Discovery packet template/);
assert.match(docPrepView, /Live Discovery packet/);
assert.match(docPrepView, /data-preview-state/);
assert.match(docPrepView, /data-s40-stream-estate/);
assert.match(docPrepView, /Live report streams/);
assert.match(docPrepView, /aria-pressed/);
assert.match(docPrepView, /data-s40-stream-window/);
assert.match(docPrepView, /data-s40-queue-search/);
assert.match(docPrepView, /s40-docprep-query/);
assert.match(docPrepView, /s40-docprep-selection/);
assert.match(docPrepView, /renderDynamicIsland/);
assert.match(docPrepView, /data-state=\"\$\{escape\(bridge, step\.state\)\}\"/);
assert.match(docPrepView, /IDI report uploaded/);
assert.match(docPrepView, /source === \"IDI report upload\"/);
assert.match(docPrepView, /function recentManualUpload\(snapshot, estateId\)/);
assert.match(docPrepView, /String\(candidate\?\.estateId \|\| \"\"\)\.trim\(\) === selectedEstateId/);
assert.match(docPrepView, /event\.updatedAt \|\| event\.at/);
assert.match(docPrepView, /recentManualUpload\(snapshot, row\.id\)/);
assert.doesNotMatch(docPrepView, /s40-stage-strip/);
assert.match(docPrepView, /select-estate.*estateId: control\.dataset\.s40StreamEstate/s);
assert.match(docPrepCss, /grid-template-columns: minmax\(0, 30%\) minmax\(0, 70%\)/);
assert.match(docPrepCss, /\.s40-docprep-empty > \.s40-workbench/);
assert.match(docPrepCss, /max-width: none/);
assert.match(docPrepCss, /@media \(max-width: 700px\)/);
assert.match(docPrepCss, /\.s40-stream-switcher/);
assert.match(docPrepCss, /\.s40-stream-switch\[aria-pressed="true"\]/);
assert.match(docPrepCss, /\.s40-dynamic-island[\s\S]*margin: 15px 0 0/);
assert.match(docPrepCss, /\.s40-dynamic-island[\s\S]*width: 100%[\s\S]*padding: 1\.5125rem 1rem/);
assert.match(docPrepCss, /@media \(min-width: 701px\)[\s\S]*margin-left: calc\(-1 \* var\(--s40-docprep-gutter\)\)/);
assert.match(docPrepCss, /@keyframes s40-island-spin/);
assert.match(docPrepCss, /\.s40-island-controls[\s\S]*margin-inline-start: auto/);
assert.match(docPrepCss, /\.s40-idi-status/);
assert.match(docPrepCss, /\.s40-discovery-page-header/);
assert.match(docPrepCss, /\.s40-discovery-page-footer/);
assert.doesNotMatch(docPrepCss, /\.s40-stage-strip/);
assert.match(docPrepCss, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(docPrepCss, /#researchRail/);
assert.match(docPrepCss, /\.s40-artifact-surface[\s\S]*border-radius: var\(--hr-radius-panel\)/);
assert.match(docPrepCss, /\.s40-discovery-paper/);
assert.match(docPrepCss, /rgb\(67 171 214\)/);
assert.match(docPrepCss, /rgb\(19 163 216\)/);
assert.match(docPrepCss, /rgb\(255 192 0\)/);
assert.match(docPrepView, /<colgroup>/);
assert.match(docPrepView, /s40-discovery-offer-description/);
assert.match(docPrepView, /discoveryPreviewFallback\(preview\)/);
assert.doesNotMatch(docPrepView, /Needs review/);
assert.doesNotMatch(docPrepView, /Run report to fetch/);
assert.match(docPrepCss, /table-layout: fixed/);
assert.match(docPrepCss, /width: 332pt/);
assert.match(docPrepCss, /width: 106pt/);
assert.match(docPrepCss, /width: 115pt/);
assert.match(docPrepCss, /width: 111pt/);
assert.doesNotMatch(docPrepCss, /scrollbar-gutter/);
assert.match(dashboardCss, /\.dashboard-attention[\s\S]*margin-top: 23px/);
assert.match(compatCss, /\.estate-file-preview \{[\s\S]*border-radius: var\(--hr-radius-control\)/);
assert.match(compatCss, /background: #000000/);
assert.match(compatCss, /background: #0a0a0a/);
assert.match(compatCss, /background: #121111/);
assert.match(compatCss, /background: #0f1115/);
assert.match(compatCss, /border-radius: 999px/);
assert.match(tokensCss, /--hr-radius-chip:\s*0\.45rem/);
assert.match(legacyCss, /\.pill\s*\{[\s\S]*?border-radius: var\(--hr-radius-chip\)/);
assert.match(legacyCss, /\.document-type-pill\s*\{[\s\S]*?border-radius: var\(--hr-radius-chip\)/);
assert.match(compatCss, /\.hr-grid-controls[\s\S]*?border-radius: var\(--hr-radius-chip\)/);
assert.match(gridCss, /\.hr-grid-row-action[\s\S]*?border-radius: var\(--hr-radius-chip\)/);
assert.match(shellCss, /\.shell-primary-command[\s\S]*?border-radius: var\(--hr-radius-chip\)/);
assert.match(shellCss, /body\[data-s38-shell="case-journey"\] button:not[\s\S]*?border-radius: var\(--hr-radius-chip\)/);
assert.match(docPrepView, /data-s40-approve/);
assert.match(docPrepView, /data-approve-packet/);
assert.match(docPrepView, /packetApproved/);

const settingsRenderBody = legacy.slice(legacy.indexOf("function renderSettingsView"));
assert.doesNotMatch(settingsRenderBody, /settingsReadinessBandHtml/);
const integrationPanelBody = legacy.slice(legacy.indexOf("function renderIntegrationSettingsPanel"), legacy.indexOf("function renderSupportSettingsPanel"));
assert.doesNotMatch(integrationPanelBody, /integrationStatusRowsHtml/);
assert.match(integrationPanelBody, /integration-directory/);
assert.doesNotMatch(integrationPanelBody, /integrationOnboardingCardHtml\("activepieces"\)/);
assert.doesNotMatch(integrationPanelBody, /integrationOnboardingCardHtml\("leads"\)/);
assert.match(legacy, /title: "Browserbase \(Public Records\)"/);
assert.match(legacy, /public record source checks are ready and reported per run/i);
assert.doesNotMatch(integrationPanelBody, /<p class="eyebrow">Integration<\/p>/);

assert.match(exportRegister, /id: "s40-estate-export"/);
assert.match(exportRegister, /id: "export"/);
assert.match(exportView, /data-beui-rail="export"/);
assert.doesNotMatch(exportView, /createCommunityGrid|data-community-grid/);
assert.match(exportView, /workflowState === "exported"/);
assert.match(operationalRails, /Verified readback/);
assert.match(shellView, /dashboard: "Manage Estates"/);
assert.match(shellView, /Go to Manage Estates/);
assert.match(shellController, /Manage Estates opened/);

for (const source of [legacy, estates, docPrepView, exportView]) {
  assert.doesNotMatch(source, /BEUI_PRO_TOKEN|process\.env\.[A-Z0-9_]*TOKEN|client secret|access token/i);
}

console.log("S40 Estates-to-Export contract passed.");
